### ISSUE TITLE
Please move tieless tracks to its own mod

### ISSUE THREAD

**Issue by Montandalar** [SamMatzko/minetest-subways#4]
I know it's cool to have them but while subways as a modpack is a decent idea to group your related trains together, a modpack like the tieless tracks stands on its own and belongs in a separate modpack.

**Comment by SamMatzko** [comment]
Hello Montandalar, thanks for the feedback! You're right, it would be better to have the tieless tracks stand on their own. I'll put them in their own mod and publish it as soon as I get the time!

**Comment by SamMatzko** [comment]
Alrighty, I finished up a few things, and I've released [Tieless Tracks on ContentDB](https://content.minetest.net/packages/sylvester_kruin/tieless_tracks/)!
